# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  S3_BUCKET_NAME: comong-java-server-01

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    
    # build 후 프로젝트 압축.
    - name: Make zip file
      run: zip -r ./comongjava-deploy.zip .
      shell: bash

    #Access key, Secret Access key 를 통해 권한 확인.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    #압축된 프로젝트 S3로 전송
    - name: Uplaod to S3
      run: aws s3 cp --region ap-northeast-2 ./comongjava-deploy.zip s3://$S3_BUCKET_NAME/comongjava-deploy.zip

    # CodeDeploy에게 배로 명령을 내립니다.
    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name comongjava-githubAction-deploy 
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name comongjava-githubAction-deployGroup
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=comongjava-deploy.zip